// Guarda los archivos de la app para abrirla rápido. Los precios NUNCA se guardan aquí: siempre se piden a tu base.
const V = 'profitgod-0.9', FILES = ['./', 'index.html', 'dashboard/styles.css?v=0.3', 'dashboard/app.js?v=0.3', 'dashboard/dom.js', 'dashboard/calc.js', 'dashboard/inicio.js', 'dashboard/ops.js', 'dashboard/tools.js', 'tools/planner.js', 'tools/enchant.js', 'tools/gold.js', 'tools/reference.js', 'tools/pricecard.js', 'dashboard/explain.js', 'data/journal.js', 'opportunity-engine/confidence.js', 'opportunity-engine/opportunity.js', 'opportunity-engine/engine.js', 'flipping/finder.js', 'opportunity-engine/config.js', 'opportunity-engine/score.js', 'opportunity-engine/craftscan.js', 'opportunity-engine/plan.js', 'history/anomalies.js', 'flipping/flipping.js', 'flipping/config.js', 'black-market/risk.js', 'data/merge.js', 'data/public.js', 'data/sources.js', 'dashboard/strat.js', 'refining/refining.js', 'profit-engine/strategies.js', 'crafting/recipes.js', 'profit-engine/profit.js', 'profit-engine/scenario.js', 'refining/returnRate.js', 'data/store.js', 'data/api.js', 'data/freshness.js', 'data/items.js', 'markets/cities.js', 'settings/defaults.js', 'icon.svg', 'manifest.webmanifest'];
self.addEventListener('install', e => e.waitUntil(caches.open(V).then(c => c.addAll(FILES)).catch(() => {})));
self.addEventListener('activate', e => e.waitUntil(caches.keys().then(k => Promise.all(k.filter(x => x !== V).map(x => caches.delete(x))))));
self.addEventListener('fetch', e => {
  const u = new URL(e.request.url);
  if (u.origin !== location.origin || e.request.method !== 'GET') return;      // tu base y cualquier otro sitio van directo a la red
  e.respondWith(fetch(e.request, { cache: 'no-cache' }).then(r => { const c = r.clone(); caches.open(V).then(x => x.put(e.request, c)); return r; }).catch(() => caches.match(e.request)));
});
